# Industrial Internet Honeypot Configuration

honeypot:
  name: "Industrial-Honeypot-LLM"
  version: "1.0.0"
  
  # Network configuration
  network:
    bind_ip: "0.0.0.0"
    ports:
      http: 80
      https: 443
      ssh: 22
      telnet: 23
      ftp: 21
      modbus: 502
      
  # LLM Configuration
  llm:
    provider: "openai"  # openai, huggingface, local
    model: "gpt-3.5-turbo"
    api_key_env: "OPENAI_API_KEY"
    max_tokens: 500
    temperature: 0.7
    
  # Attack Detection
  detection:
    enabled: true
    sensitivity: "medium"  # low, medium, high
    patterns:
      sql_injection: true
      xss: true
      command_injection: true
      brute_force: true
      port_scan: true
      
  # Response Strategy
  response:
    mode: "dynamic"  # static, dynamic, learning
    delay_min: 1.0
    delay_max: 5.0
    fake_vulnerability_rate: 0.3
    
  # Logging
  logging:
    level: "INFO"
    file: "logs/honeypot.log"
    max_size: "100MB"
    backup_count: 5
    console: true
    
  # Security
  security:
    rate_limit: 100  # requests per minute per IP
    block_duration: 3600  # seconds
    whitelist: []
    blacklist: []